spring.application.name=LeaveManagementSystem

# ===============================
# DATABASE CONFIGURATION
# ===============================

# Default database (recommended for new users)
# Create this database before running:
# CREATE DATABASE leave_management_db;

spring.datasource.url=jdbc:mysql://localhost:3306/leave_management_db
spring.datasource.username=root

# Update this password based on your local MySQL setup
spring.datasource.password=Changepass@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# DATA INITIALIZATION
# ===============================

# Ensures data.sql runs on startup
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true